/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.BorderLayout;
import java.awt.Component;
import java.io.File;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import ui.colormap.ColorMap;
import ui.colormap.gradient.GradientPanel;
import ui.colormap.panel.PlattePanel;
import ui.colormap.point.PointPanel;
import ui.colormap.step.StepPanel;
import ui.colormap.MapType;

/**
 *
 * @author allanlee
 */
public abstract class PlatteEditor extends javax.swing.JPanel {

    public PlatteEditor(ColorMap mg) {
        initComponents();
        this.tabbedPn.addTab("调色板", new GradientPanel(mg));
        this.tabbedPn.addTab("指定间隔调色板", new StepPanel(mg));
        this.tabbedPn.addTab("点值调色板", new PointPanel(mg));
        this.tabbedPn.setSelectedIndex((mg == null || mg.getMapType().compareTo(MapType.Gradient) == 0) ? 0 : (mg.getMapType().compareTo(MapType.Step) == 0 ? 1 : 2));
    }

    public PlatteEditor() {
        this(null);
    }

    public static void main(String[] args) {
        JDialog dlg = new JDialog();
        PlatteEditor editor = new PlatteEditor() {
            @Override
            public void apply(ColorMap cmm) {

            }
        };
        dlg.add(editor, BorderLayout.CENTER);
        dlg.pack();
        dlg.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        toolBar = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        appleBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        operationPnl = new javax.swing.JPanel();
        tabbedPn = new javax.swing.JTabbedPane();

        setLayout(new java.awt.BorderLayout());

        toolBar.setOrientation(javax.swing.SwingConstants.VERTICAL);
        toolBar.setRollover(true);

        jPanel1.setMaximumSize(new java.awt.Dimension(75, 70));
        jPanel1.setMinimumSize(new java.awt.Dimension(75, 70));
        jPanel1.setPreferredSize(new java.awt.Dimension(75, 70));

        appleBtn.setText("应用");
        appleBtn.setFocusable(false);
        appleBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        appleBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        appleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appleBtnActionPerformed(evt);
            }
        });
        jPanel1.add(appleBtn);

        saveBtn.setText("保存");
        saveBtn.setFocusable(false);
        saveBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        jPanel1.add(saveBtn);

        toolBar.add(jPanel1);

        operationPnl.setMaximumSize(new java.awt.Dimension(75, 6777));
        operationPnl.setPreferredSize(new java.awt.Dimension(75, 190));
        toolBar.add(operationPnl);

        add(toolBar, java.awt.BorderLayout.WEST);

        tabbedPn.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabbedPnStateChanged(evt);
            }
        });
        add(tabbedPn, java.awt.BorderLayout.CENTER);
        tabbedPn.getAccessibleContext().setAccessibleName("platte");
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new FileFilter() {

            @Override
            public boolean accept(File f) {
                return f.isDirectory() || f.getPath().endsWith("cmp");
            }

            @Override
            public String getDescription() {
                return "*.cmp";
            }
        });
        int type = chooser.showSaveDialog(this);
        if (type == JFileChooser.APPROVE_OPTION) {
            String path = chooser.getSelectedFile().getPath();
            if (!path.endsWith(".cmp")) {
                path += ".cmp";
            }
            ((PlattePanel) tabbedPn.getSelectedComponent()).save(path);
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void appleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appleBtnActionPerformed
        apply(((PlattePanel) tabbedPn.getSelectedComponent()).getColorMap());
    }//GEN-LAST:event_appleBtnActionPerformed

    private void tabbedPnStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabbedPnStateChanged
        operationPnl.removeAll();
        Component sc = tabbedPn.getSelectedComponent();
        if (sc instanceof PlattePanel) {
            PlattePanel pnl = (PlattePanel) sc;
            JComponent[] buttons = pnl.getButtons();
            for (JComponent button : buttons) {
                operationPnl.add(button);
            }
        }
        operationPnl.updateUI();
    }//GEN-LAST:event_tabbedPnStateChanged

    public abstract void apply(ColorMap cmm);

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appleBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel operationPnl;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTabbedPane tabbedPn;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables

}
